#!/bin/sh
gitleaksEnabled=$(git config --bool hooks.gitleaks)
if [ "$gitleaksEnabled"="true" ]; then
        gitleaks detect -v
        if [ $? -eq 1 ]; then
                echo"Error: gitleaks has detected sensitive information in yourchanges."
                echo"If you know what you are doing you can disable this check using:"
                echo"   git config hooks.gitleaks false"
                exit 1
        fi
fi
